### ISSUE TITLE
How can I suppress the output when activating Logitacker?

### ISSUE THREAD

**Issue by git-minix** [RoganDawes/LOGITacker#61]
When I am connect with

`$ screen / dev / ttyACM0 19200`

, I am immediately spammed with INFO messages because LOGITacker starts with auto discovery. How can i stop this? You don't even get to use the commands because messages are constantly being output. Seems like a good solution logitacker-script, which I found on youtube (https://www.youtube.com/watch?v=_NgOmR0l1p0&t=72s) - but there is no link to that script. 

Is there any way to start quite?  What single command stop the discovery? Is there an option to do the cli interactions and the output in different channels? Or something like in the video (logitacker-script) with two separate terminal windows?

Frank

**Comment by git-minix** [comment]
guess this helps

`$ log backend m_cli_cdc_acm_log_backend halt`

**Comment by frame84** [comment]
```
LOGITacker (discover) $ log disable 
LOGITacker (discover) $ 
```
