### ISSUE TITLE
Adding support NRF52840

### ISSUE THREAD

**Issue by DRCRecoveryData** [RoganDawes/LOGITacker#65]
Hi,

I have update cheap dongle support logitacker firmware

NRF52840 RF Module E104-BT5040U 2.4GHz PCB BLE5.0 BLE 4.2 Onboard Antenna USB Interface High-Performance Secondary Development

https://a.aliexpress.com/_mtMbCz

## Flash over SPI using a Raspberry PI 4

![image](https://github.com/RoganDawes/LOGITacker/assets/85211068/436a6e9a-fc75-40bb-942b-8ef1fb2a3b02)

To flash the nRF24LU1+ using a Raspberry PI 4, you can connect the following pins:

| Name  | Raspberry PI 4 Pin | nRF24LU1+ Pin |
|-------|-------------------|--------------|
| GND   | 6                 | GND          |
| VCC   | 2                 | VDD          |
| PROG  | 18                | PROG         |
| SCK   | 23                | SCK          |
| MOSI  | 19                | MOSI         |
| MISO  | 21                | MISO         |
| CSN   | 24                | CSN          |

https://github.com/ShigemoriHakura/nRF24LU1P_SPI_Flashing

https://github.com/ahtn/nrf24lu1p-512-bootloader

update bootloader.hex in option 0 of
https://github.com/ShigemoriHakura/nRF24LU1P_SPI_Flashing

and upload full image dongle.bin in option 1 from:

https://github.com/RoganDawes/nrf-research-firmware

NRF24lU1P

![image](https://github.com/RoganDawes/LOGITacker/assets/85211068/72425dbe-1601-4f33-b014-23de908c4908)

![image](https://github.com/RoganDawes/LOGITacker/assets/85211068/cd16582a-7501-4d68-a15f-62b93426bfee)

![image](https://github.com/RoganDawes/LOGITacker/assets/85211068/d2edaf10-6e0e-4ced-8062-f4f66819769b)

NRF52840

![image](https://github.com/RoganDawes/LOGITacker/assets/85211068/dae811df-6724-45b1-b4e7-75e4ea8a2cd0)

**Comment by RoganDawes** [comment]
Not 100% sure what your point is. You mention flashing the 52840 dongle, but the bulk of your post is about flashing a 24lu1 dongle instead. Does that get a Logitech firmware to act as a receiver? Were there any changes required to get the LOGITACKER firmware working on the 52840 dongle?
