### ISSUE TITLE
Having trouble of installation of LOGITacker

### ISSUE THREAD

**Issue by ph-payas0** [RoganDawes/LOGITacker#66]
Hi i have a trouble of installing the LOGITacker.

I'm using C-U0012 dongle ( LogiTech ). Can you elaborate' how can I access the logitacker cli using this dongle please? Do I need to flash another firmware aside from munifying tool?

**Comment by RoganDawes** [comment]
You need to have a device with a Nordic NRF52840 on it to run LOGITacker. It can then interface with various Logitech dongles, either directly via pairing, or "surreptitiously" via message injection.
