### ISSUE TITLE
[Feature request] Option to disable leds blinking

### ISSUE THREAD

**Issue by xxxcrow** [RoganDawes/LOGITacker#68]
Would be nice to disable the LEDs
They look awesome and very satisfying to look at
But an option to disable them would probably be easy and useful

**Comment by RoganDawes** [comment]
Keep in mind that the LOGITacker dongle is on your side, not your "target's". So having flashing lights is less of an issue when it comes to drawing attention. Worst case, a little tape over the lights should do the trick, or even some heatshrink tubing.
That said, I am not the original developer of this firmware, just a custodian/user, and I'm not really in a position to do development on it. Sorry.
