### ISSUE TITLE
All devices display almost the same info, and can't do anything with them

### ISSUE THREAD

**Issue by xxxcrow** [RoganDawes/LOGITacker#69]
Hi, all devices I find display as:
```
'unknown name' keyboard: no mouse: no                           class: Logitech Unifying compatible device WPID: 0x0000 dongle WPID: 0x0000
```
Or:
```
'unknown name' keyboard: yes mouse: no                           class: Logitech Unifying compatible device WPID: 0x0000 dongle WPID: 0x0000
```
Or:
```
'unknown name' keyboard: no mouse: yes                           class: Logitech Unifying compatible device WPID: 0x0000 dongle WPID: 0x0000
```

Question 
Number 1: is it ok?
Number 2: what are these devices?
Number 3: when I try passive/active enumerate the output is the same for all devices: timeout after 1300ms

edit: sorry for tagging other issues

**Comment by RoganDawes** [comment]
Don't think I have seen this before. Are you sure that you are picking up actual Logitech devices? Could there possibly be other brand wireless devices around you?

**Comment by xxxcrow** [comment]
@RoganDawes I don't know if these are real Logitech devices, because I don't have any 
But I travel to a lot of places and everything I find is like that
Sometimes I find none, sometimes 4-5-6
It has more logs, about the correct device, but an empty frame

**Comment by RoganDawes** [comment]
Can I suggest buying a cheap Logitech mouse with Unifying receiver to use as a testbed? That way you will know whether you are dealing with a real Logitech device, and what to expect LOGITacker to display when you see other devices in the field.

**Comment by xxxcrow** [comment]
@RoganDawes shouldn't non-Logitech devices be filtered? 🤔
The logs say something about correct signature and add the devices to the list
But some get filtered
Doesn't it mean the filter is not working? 🙄
